### ISSUE TITLE
Ansible-galaxy install version detection problem

### ISSUE THREAD

**Issue by kkremitzki** [juju4/ansible-lxd#3]
When I try `ansible-galaxy install juju4.lxd`, I get:
```
- downloading role 'lxd', owned by juju4
 [WARNING]: - juju4.lxd was NOT installed successfully: Unable to compare role versions (v0.8, 0.9.0) to determine the
most recent version due to incompatible version formats. Please contact the role author to resolve versioning
conflicts, or specify an explicit role version to install.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

```

**Comment by juju4** [comment]
This is a problem with Galaxy. They say semantic versioning only but are mixing stuff in practice
https://github.com/juju4/ansible-redhat-epel/issues/1
https://github.com/ansible/galaxy/issues/1574

workaround in your requirements file, require master or latest tag manually (0.9.0 here)
```
- src: https://github.com/bennojoy/nginx
  version: master
  name: nginx_role
```
from https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html
or directly use github, which allows to update.

**Comment by juju4** [comment]
This should be fully fixed now.
old tags were renamed for semantic versioning and latest is 1.0.0
